// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDV0NRejUtrlzXPmVtAjzBkZzbt6rA0I',
    appId: '1:780152238922:web:50f424e805702af3c2c7b3',
    messagingSenderId: '780152238922',
    projectId: 'shetkari-raja-1e0e5',
    authDomain: 'shetkari-raja-1e0e5.firebaseapp.com',
    storageBucket: 'shetkari-raja-1e0e5.firebasestorage.app',
    measurementId: 'G-2V1KSXMWBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoPdvvc8REyxEzaeEo3wX4-m5faTGrEg',
    appId: '1:780152238922:android:c15008865ba69294c2c7b3',
    messagingSenderId: '780152238922',
    projectId: 'shetkari-raja-1e0e5',
    storageBucket: 'shetkari-raja-1e0e5.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_4jQxKHaw_6xiYwKXxRKnVxG8_SJXac',
    appId: '1:780152238922:ios:d7542dc65460b60cc2c7b3',
    messagingSenderId: '780152238922',
    projectId: 'shetkari-raja-1e0e5',
    storageBucket: 'shetkari-raja-1e0e5.firebasestorage.app',
    iosBundleId: 'com.example.agronew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqDV0NRejUtrlzXPmVtAjzBkZzbt6rA0I',
    appId: '1:780152238922:web:8b27aa938006ecf2c2c7b3',
    messagingSenderId: '780152238922',
    projectId: 'shetkari-raja-1e0e5',
    authDomain: 'shetkari-raja-1e0e5.firebaseapp.com',
    storageBucket: 'shetkari-raja-1e0e5.firebasestorage.app',
    measurementId: 'G-0BQZW25T87',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_4jQxKHaw_6xiYwKXxRKnVxG8_SJXac',
    appId: '1:780152238922:ios:d7542dc65460b60cc2c7b3',
    messagingSenderId: '780152238922',
    projectId: 'shetkari-raja-1e0e5',
    storageBucket: 'shetkari-raja-1e0e5.firebasestorage.app',
    iosBundleId: 'com.example.agronew',
  );

}